# Generated by Django 4.1.6 on 2023-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_post_views_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
