# Generated by Django 4.1.6 on 2023-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
