# Generated by Django 4.1.6 on 2023-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('comment_text', 'post')},
        ),
    ]
