# Generated by Django 4.1.6 on 2023-02-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_alter_comment_options_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('comment_text', 'id')},
        ),
    ]
